language: android

# Needs sudo to build
sudo: required

android:
  components:
    - build-tools-21.1.2
    - sys-img-armeabi-v7a-android-22
    - android-22
    - extra-android-support
    - platform-tools
    - tools
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  # Give gradlew write permission (needed to download dependencies)
  - chmod +x gradlew

# Emulator Management: Create, Start and Wait
before_script:
  - android list sdk --extended --no-ui --all
  - echo no | android create avd --force -n test -t "android-22" --abi "default/armeabi-v7a"
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache